<a href="https://colab.research.google.com/github/mehta-aditya13191/Machine-Learning/blob/main/01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy->Numerical python

# AdvanTages
  1.Allow several Mathematical operations
  2.Faster operations

In [1]:
import numpy as np


ModuleNotFoundError: No module named 'numpy'

List vs Numpy->Time Taken

In [ ]:
from time import process_time

Time taken by a list


In [ ]:
List=[i for i in range(10000)]
start_time=process_time()

List=[i+5 for i in List]

end_time=process_time()

print("total Time Taken: ",end_time-start_time)

total Time Taken:  0.0008631410000017326


In [ ]:
np_array=np.array([i for i in range(10000)])
start_time=process_time()
np_array+=5
end_time=process_time()
print("total Time Taken: ",end_time-start_time)


total Time Taken:  0.00019594299999958764


Numpy Arrays

In [ ]:
# list
list1=[1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array=np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
# creating 1 dim array
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a.shape

(4,)

In [ ]:
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)
print(b.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [ ]:
b=np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(b)


[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Intial placeholder in numpy arrays

In [ ]:
# create a numpy array of zeros
x=np.zeros((4,5))
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# create a numpy array of ones
y=np.ones((3,3))
y


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# array of a particular value
z=np.full((5,4),5)
z

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [ ]:
# creating an identity matrix
I=np.eye(4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# create a numpy array with random values
b=np.random.random((3,4))
b

array([[0.93157497, 0.90350193, 0.73755079, 0.30344015],
       [0.61418627, 0.35175644, 0.8072261 , 0.01766638],
       [0.35409225, 0.65980974, 0.82362207, 0.91190695]])

In [ ]:
# random integer values array  within a specific range
c=np.random.randint(10,100,(3,5))
c

array([[96, 91, 54, 52, 31],
       [77, 71, 43, 94, 50],
       [18, 83, 66, 34, 59]])

In [ ]:
#  array of evenly spaced values -->specifying the number of values required
d=np.linspace(10,30,6)
d

array([10., 14., 18., 22., 26., 30.])

In [ ]:
# array of evenly spaced values --> specifying the steps
e=np.arange(10,30,6)
e

array([10, 16, 22, 28])

In [ ]:
#  convert a list to numpy array
list2=[10,20,40,50]

np_array=np.asarray(list2)
print(np_array)
type(np_array)

[10 20 40 50]


numpy.ndarray

Analysing a numpy array

In [ ]:
c=np.random.randint(10,90,(5,5))
c

array([[20, 52, 76, 53, 35],
       [50, 84, 87, 24, 79],
       [60, 65, 64, 41, 29],
       [59, 31, 68, 60, 16],
       [73, 77, 13, 51, 61]])

In [ ]:
#  array dimension
c.shape

(5, 5)

In [ ]:
# number of dimensions
print(c.ndim)

2


In [ ]:
#  checking the number of elements in an array
print(c.size)

25


In [ ]:
# cheking the data type of the values in the array
print(c.dtype)

int64


Mathematical operations on np array

In [ ]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]

print(list1+list2) #concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))


In [ ]:
print(a)
print(b)

[[4 4 0]
 [6 7 9]
 [4 8 6]]
[[13 18 10]
 [10 19 19]
 [10 19 18]]


In [ ]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[17 22 10]
 [16 26 28]
 [14 27 24]]
[[ -9 -14 -10]
 [ -4 -12 -10]
 [ -6 -11 -12]]
[[ 52  72   0]
 [ 60 133 171]
 [ 40 152 108]]
[[0.30769231 0.22222222 0.        ]
 [0.6        0.36842105 0.47368421]
 [0.4        0.42105263 0.33333333]]


In [ ]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[17 22 10]
 [16 26 28]
 [14 27 24]]
[[ -9 -14 -10]
 [ -4 -12 -10]
 [ -6 -11 -12]]
[[ 52  72   0]
 [ 60 133 171]
 [ 40 152 108]]
[[0.30769231 0.22222222 0.        ]
 [0.6        0.36842105 0.47368421]
 [0.4        0.42105263 0.33333333]]


Array manipulation

In [ ]:
array=np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[1 4 0]
 [8 0 5]]
(2, 3)


In [ ]:
# transpose of the matrix
trans=np.transpose(array)
print(trans)
print(trans.shape)

[[1 8]
 [4 0]
 [0 5]]
(3, 2)


In [ ]:
trans2=array.T
print(trans2)
print(trans2.shape)

[[1 8]
 [4 0]
 [0 5]]
(3, 2)
